wandb_version: 1

number of generations:
  desc: null
  value: 200
generation size:
  desc: null
  value: 320
mutation level:
  desc: null
  value: 0.05
cross-over level:
  desc: null
  value: 0.5
mutation description:
  desc: null
  value: unchanged
crossover description:
  desc: null
  value: unchanged
score methode:
  desc: null
  value: faze 3 - check max tile in corner (if not -10) +increasing row (if true +20)
    + extrapower to the tile
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710069264.145489
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.11
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
