wandb_version: 1

number of generations:
  desc: null
  value: 250
generation size:
  desc: null
  value: 80
mutation level:
  desc: null
  value: 0.05
cross-over level:
  desc: null
  value: 0.5
mutation description:
  desc: null
  value: sdfsdf
crossover description:
  desc: null
  value: Asdsad
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708776180.544424
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.11
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
